on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:
jobs:
  call-workflow-passing-data:
    uses: ideag/atomic-deploys-action/.github/workflows/atomic.yml@main
    with:
      host: ${{ inputs.host }}
      ## port: ${{ inputs.port }}
      port: 22
      dir: /home/master/applications/dfbhjjumxe/public_html/wp-content/lifejacket-server
    secrets:
      username: ${{ secrets.user }}
      key: ${{ secrets.key }}
